#!/usr/bin/python3
"""
Adds the State object 'Louisiana' to the database hbtn_0e_6_usa.
Prints the new state's id after creation.
"""
import sys
from model_state import Base, State
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker


if __name__ == "__main__":
    # Create engine to connect to the MySQL server
    engine = create_engine(
        'mysql+mysqldb://{}:{}@localhost:3306/{}'.format(
            sys.argv[1], sys.argv[2], sys.argv[3]
        ),
        pool_pre_ping=True
    )

    # Setup session
    Session = sessionmaker(bind=engine)
    session = Session()

    # Create a new State instance
    new_state = State(name="Louisiana")

    # Add the new object to the session (it's now in 'pending' state)
    session.add(new_state)

    # Commit the transaction to save changes to the database
    session.commit()

    # After commit, the object is updated with the id generated by MySQL
    print("{}".format(new_state.id))

    # Close the session
    session.close()
